/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.evento.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.PepqaAppV3.evento.logic.dto.EventoPageDTO;
import co.edu.uniandes.csw.PepqaAppV3.evento.logic.dto.EventoDTO;
import co.edu.uniandes.csw.PepqaAppV3.evento.persistence.api.IEventoPersistence;
import co.edu.uniandes.csw.PepqaAppV3.evento.persistence.entity.EventoEntity;
import co.edu.uniandes.csw.PepqaAppV3.evento.persistence.converter.EventoConverter;
import static co.edu.uniandes.csw.PepqaAppV3.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EventoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EventoPersistence.class.getPackage())
				.addPackage(EventoEntity.class.getPackage())
				.addPackage(IEventoPersistence.class.getPackage())
                .addPackage(EventoDTO.class.getPackage())
                .addPackage(EventoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEventoPersistence eventoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EventoEntity").executeUpdate();
	}

	private List<EventoEntity> data=new ArrayList<EventoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EventoEntity entity=new EventoEntity();
			entity.setDescripcion(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEventoTest(){
		EventoDTO dto=new EventoDTO();
		dto.setDescripcion(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		EventoDTO result=eventoPersistence.createEvento(dto);
		
		Assert.assertNotNull(result);
		
		EventoEntity entity=em.find(EventoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getName(), entity.getName());
	}
	
	@Test
	public void getEventosTest(){
		List<EventoDTO> list=eventoPersistence.getEventos();
		Assert.assertEquals(list.size(), data.size());
        for(EventoDTO dto:list){
        	boolean found=false;
            for(EventoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEventoTest(){
		EventoEntity entity=data.get(0);
		EventoDTO dto=eventoPersistence.getEvento(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getName(), dto.getName());
        
	}
	
	@Test
	public void deleteEventoTest(){
		EventoEntity entity=data.get(0);
		eventoPersistence.deleteEvento(entity.getId());
        EventoEntity deleted=em.find(EventoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEventoTest(){
		EventoEntity entity=data.get(0);
		
		EventoDTO dto=new EventoDTO();
		dto.setId(entity.getId());
		dto.setDescripcion(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		
		
		eventoPersistence.updateEvento(dto);
		
		
		EventoEntity resp=em.find(EventoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getName(), resp.getName());	
	}
	
	@Test
	public void getEventoPaginationTest(){
		//Page 1
		EventoPageDTO dto1=eventoPersistence.getEventos(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        EventoPageDTO dto2=eventoPersistence.getEventos(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(EventoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(EventoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EventoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EventoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}