/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.dto.PepqaAppDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.dto.PepqaAppPageDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.api._IPepqaAppPersistence;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.converter.PepqaAppConverter;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.entity.PepqaAppEntity;

public abstract class _PepqaAppPersistence implements _IPepqaAppPersistence {

  	@PersistenceContext(unitName="PepqaAppV3PU")
 
	protected EntityManager entityManager;
	
	public PepqaAppDTO createPepqaApp(PepqaAppDTO pepqaApp) {
		PepqaAppEntity entity=PepqaAppConverter.persistenceDTO2Entity(pepqaApp);
		entityManager.persist(entity);
		return PepqaAppConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<PepqaAppDTO> getPepqaApps() {
		Query q = entityManager.createQuery("select u from PepqaAppEntity u");
		return PepqaAppConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public PepqaAppPageDTO getPepqaApps(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from PepqaAppEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from PepqaAppEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		PepqaAppPageDTO response = new PepqaAppPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(PepqaAppConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public PepqaAppDTO getPepqaApp(Long id) {
		return PepqaAppConverter.entity2PersistenceDTO(entityManager.find(PepqaAppEntity.class, id));
	}

	public void deletePepqaApp(Long id) {
		PepqaAppEntity entity=entityManager.find(PepqaAppEntity.class, id);
		entityManager.remove(entity);
	}

	public void updatePepqaApp(PepqaAppDTO detail) {
		PepqaAppEntity entity=entityManager.merge(PepqaAppConverter.persistenceDTO2Entity(detail));
		PepqaAppConverter.entity2PersistenceDTO(entity);
	}

}