/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.dto.PepqaAppDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.dto.PepqaAppPageDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.api._IPepqaAppLogicService;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.api.IPepqaAppPersistence;

public abstract class _PepqaAppLogicService implements _IPepqaAppLogicService {

	@Inject
	protected IPepqaAppPersistence persistance;

	public PepqaAppDTO createPepqaApp(PepqaAppDTO pepqaApp){
		return persistance.createPepqaApp( pepqaApp); 
    }

	public List<PepqaAppDTO> getPepqaApps(){
		return persistance.getPepqaApps(); 
	}

	public PepqaAppPageDTO getPepqaApps(Integer page, Integer maxRecords){
		return persistance.getPepqaApps(page, maxRecords); 
	}

	public PepqaAppDTO getPepqaApp(Long id){
		return persistance.getPepqaApp(id); 
	}

	public void deletePepqaApp(Long id){
	    persistance.deletePepqaApp(id); 
	}

	public void updatePepqaApp(PepqaAppDTO pepqaApp){
	    persistance.updatePepqaApp(pepqaApp); 
	}	
}