/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.usuario.master.logic.dto;

import co.edu.uniandes.csw.PepqaAppV3.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.PepqaAppV3.evento.logic.dto.EventoDTO;
import co.edu.uniandes.csw.PepqaAppV3.usuario.logic.dto.UsuarioDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _UsuarioMasterDTO {

 
    protected UsuarioDTO usuarioEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public UsuarioDTO getUsuarioEntity() {
        return usuarioEntity;
    }

    public void setUsuarioEntity(UsuarioDTO usuarioEntity) {
        this.usuarioEntity = usuarioEntity;
    }
    
    public List<UsuarioDTO> createcontactoUs;
    public List<UsuarioDTO> updatecontactoUs;
    public List<UsuarioDTO> deletecontactoUs;
    public List<UsuarioDTO> listcontactoUs;	
    public List<EventoDTO> createeventosUs;
    public List<EventoDTO> updateeventosUs;
    public List<EventoDTO> deleteeventosUs;
    public List<EventoDTO> listeventosUs;	
	
	
	
    public List<UsuarioDTO> getCreatecontactoUs(){ return createcontactoUs; };
    public void setCreatecontactoUs(List<UsuarioDTO> createcontactoUs){ this.createcontactoUs=createcontactoUs; };
    public List<UsuarioDTO> getUpdatecontactoUs(){ return updatecontactoUs; };
    public void setUpdatecontactoUs(List<UsuarioDTO> updatecontactoUs){ this.updatecontactoUs=updatecontactoUs; };
    public List<UsuarioDTO> getDeletecontactoUs(){ return deletecontactoUs; };
    public void setDeletecontactoUs(List<UsuarioDTO> deletecontactoUs){ this.deletecontactoUs=deletecontactoUs; };
    public List<UsuarioDTO> getListcontactoUs(){ return listcontactoUs; };
    public void setListcontactoUs(List<UsuarioDTO> listcontactoUs){ this.listcontactoUs=listcontactoUs; };	
    public List<EventoDTO> getCreateeventosUs(){ return createeventosUs; };
    public void setCreateeventosUs(List<EventoDTO> createeventosUs){ this.createeventosUs=createeventosUs; };
    public List<EventoDTO> getUpdateeventosUs(){ return updateeventosUs; };
    public void setUpdateeventosUs(List<EventoDTO> updateeventosUs){ this.updateeventosUs=updateeventosUs; };
    public List<EventoDTO> getDeleteeventosUs(){ return deleteeventosUs; };
    public void setDeleteeventosUs(List<EventoDTO> deleteeventosUs){ this.deleteeventosUs=deleteeventosUs; };
    public List<EventoDTO> getListeventosUs(){ return listeventosUs; };
    public void setListeventosUs(List<EventoDTO> listeventosUs){ this.listeventosUs=listeventosUs; };	
	
	
}

