/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.pepqaapp.master.persistence;
import co.edu.uniandes.csw.PepqaAppV3.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.master.persistence.entity.PepqaAppusuariosEntity;
import co.edu.uniandes.csw.PepqaAppV3.usuario.persistence.converter.UsuarioConverter;
import co.edu.uniandes.csw.PepqaAppV3.evento.logic.dto.EventoDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.master.persistence.entity.PepqaAppeventosEntity;
import co.edu.uniandes.csw.PepqaAppV3.evento.persistence.converter.EventoConverter;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.dto.PepqaAppDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.master.logic.dto.PepqaAppMasterDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.master.persistence.api._IPepqaAppMasterPersistence;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.api.IPepqaAppPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _PepqaAppMasterPersistence implements _IPepqaAppMasterPersistence {

  	@PersistenceContext(unitName="PepqaAppV3PU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IPepqaAppPersistence pepqaappPersistence;  

    public PepqaAppMasterDTO getPepqaApp(Long pepqaappId) {
        PepqaAppMasterDTO pepqaappMasterDTO = new PepqaAppMasterDTO();
        PepqaAppDTO pepqaapp = pepqaappPersistence.getPepqaApp(pepqaappId);
        pepqaappMasterDTO.setPepqaAppEntity(pepqaapp);
        pepqaappMasterDTO.setListusuarios(getPepqaAppusuariosEntityList(pepqaappId));
        pepqaappMasterDTO.setListeventos(getPepqaAppeventosEntityList(pepqaappId));
        return pepqaappMasterDTO;
    }

    public PepqaAppusuariosEntity createPepqaAppusuariosEntity(PepqaAppusuariosEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deletePepqaAppusuariosEntity(Long pepqaAppId, Long usuariosId) {
        Query q = entityManager.createNamedQuery("PepqaAppusuariosEntity.deletePepqaAppusuariosEntity");
        q.setParameter("pepqaAppId", pepqaAppId);
        q.setParameter("usuariosId", usuariosId);
        q.executeUpdate();
    }

    public List<UsuarioDTO> getPepqaAppusuariosEntityList(Long pepqaAppId) {
        ArrayList<UsuarioDTO> resp = new ArrayList<UsuarioDTO>();
        Query q = entityManager.createNamedQuery("PepqaAppusuariosEntity.getByMasterId");
        q.setParameter("pepqaAppId",pepqaAppId);
        List<PepqaAppusuariosEntity> qResult =  q.getResultList();
        for (PepqaAppusuariosEntity entity : qResult) { 
            if(entity.getUsuariosIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(UsuarioConverter.entity2PersistenceDTO(entity.getUsuariosIdEntity()));
        }
        return resp;
    }
    public PepqaAppeventosEntity createPepqaAppeventosEntity(PepqaAppeventosEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deletePepqaAppeventosEntity(Long pepqaAppId, Long eventosId) {
        Query q = entityManager.createNamedQuery("PepqaAppeventosEntity.deletePepqaAppeventosEntity");
        q.setParameter("pepqaAppId", pepqaAppId);
        q.setParameter("eventosId", eventosId);
        q.executeUpdate();
    }

    public List<EventoDTO> getPepqaAppeventosEntityList(Long pepqaAppId) {
        ArrayList<EventoDTO> resp = new ArrayList<EventoDTO>();
        Query q = entityManager.createNamedQuery("PepqaAppeventosEntity.getByMasterId");
        q.setParameter("pepqaAppId",pepqaAppId);
        List<PepqaAppeventosEntity> qResult =  q.getResultList();
        for (PepqaAppeventosEntity entity : qResult) { 
            if(entity.getEventosIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EventoConverter.entity2PersistenceDTO(entity.getEventosIdEntity()));
        }
        return resp;
    }

}
