/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.usuario.master.persistence;
import co.edu.uniandes.csw.PepqaAppV3.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.PepqaAppV3.usuario.master.persistence.entity.UsuariocontactoUsEntity;
import co.edu.uniandes.csw.PepqaAppV3.usuario.persistence.converter.UsuarioConverter;
import co.edu.uniandes.csw.PepqaAppV3.evento.logic.dto.EventoDTO;
import co.edu.uniandes.csw.PepqaAppV3.usuario.master.persistence.entity.UsuarioeventosUsEntity;
import co.edu.uniandes.csw.PepqaAppV3.evento.persistence.converter.EventoConverter;
import co.edu.uniandes.csw.PepqaAppV3.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.PepqaAppV3.usuario.master.logic.dto.UsuarioMasterDTO;
import co.edu.uniandes.csw.PepqaAppV3.usuario.master.persistence.api._IUsuarioMasterPersistence;
import co.edu.uniandes.csw.PepqaAppV3.usuario.persistence.api.IUsuarioPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _UsuarioMasterPersistence implements _IUsuarioMasterPersistence {

  	@PersistenceContext(unitName="PepqaAppV3PU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IUsuarioPersistence usuarioPersistence;  

    public UsuarioMasterDTO getUsuario(Long usuarioId) {
        UsuarioMasterDTO usuarioMasterDTO = new UsuarioMasterDTO();
        UsuarioDTO usuario = usuarioPersistence.getUsuario(usuarioId);
        usuarioMasterDTO.setUsuarioEntity(usuario);
        usuarioMasterDTO.setListcontactoUs(getUsuariocontactoUsEntityList(usuarioId));
        usuarioMasterDTO.setListeventosUs(getUsuarioeventosUsEntityList(usuarioId));
        return usuarioMasterDTO;
    }
    
    public UsuariocontactoUsEntity createUsuariocontactoUsEntity(UsuariocontactoUsEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteUsuariocontactoUsEntity(Long usuarioId, Long contactoUsId) {
        Query q = entityManager.createNamedQuery("UsuariocontactoUsEntity.deleteUsuariocontactoUsEntity");
        q.setParameter("usuarioId", usuarioId);
        q.setParameter("contactoUsId", contactoUsId);
        q.executeUpdate();
    }

    public List<UsuarioDTO> getUsuariocontactoUsEntityList(Long usuarioId) {
        ArrayList<UsuarioDTO> resp = new ArrayList<UsuarioDTO>();
        Query q = entityManager.createNamedQuery("UsuariocontactoUsEntity.getByMasterId");
        q.setParameter("usuarioId",usuarioId);
        List<UsuariocontactoUsEntity> qResult =  q.getResultList();
        for (UsuariocontactoUsEntity entity : qResult) { 
            if(entity.getContactoUsIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(UsuarioConverter.entity2PersistenceDTO(entity.getContactoUsIdEntity()));
        }
        return resp;
    }
    public UsuarioeventosUsEntity createUsuarioeventosUsEntity(UsuarioeventosUsEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteUsuarioeventosUsEntity(Long usuarioId, Long eventosUsId) {
        Query q = entityManager.createNamedQuery("UsuarioeventosUsEntity.deleteUsuarioeventosUsEntity");
        q.setParameter("usuarioId", usuarioId);
        q.setParameter("eventosUsId", eventosUsId);
        q.executeUpdate();
    }

    public List<EventoDTO> getUsuarioeventosUsEntityList(Long usuarioId) {
        ArrayList<EventoDTO> resp = new ArrayList<EventoDTO>();
        Query q = entityManager.createNamedQuery("UsuarioeventosUsEntity.getByMasterId");
        q.setParameter("usuarioId",usuarioId);
        List<UsuarioeventosUsEntity> qResult =  q.getResultList();
        for (UsuarioeventosUsEntity entity : qResult) { 
            if(entity.getEventosUsIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EventoConverter.entity2PersistenceDTO(entity.getEventosUsIdEntity()));
        }
        return resp;
    }

}
