/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.dto.PepqaAppPageDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.dto.PepqaAppDTO;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.logic.api.IPepqaAppLogicService;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.PepqaAppPersistence;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.api.IPepqaAppPersistence;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.entity.PepqaAppEntity;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.converter.PepqaAppConverter;
import static co.edu.uniandes.csw.PepqaAppV3.util._TestUtil.*;

@RunWith(Arquillian.class)
public class PepqaAppLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(PepqaAppLogicService.class.getPackage())
				.addPackage(IPepqaAppLogicService.class.getPackage())
				.addPackage(PepqaAppPersistence.class.getPackage())
				.addPackage(PepqaAppEntity.class.getPackage())
				.addPackage(IPepqaAppPersistence.class.getPackage())
                .addPackage(PepqaAppDTO.class.getPackage())
                .addPackage(PepqaAppConverter.class.getPackage())
                .addPackage(PepqaAppEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IPepqaAppLogicService pepqaAppLogicService;
	
	@Inject
	private IPepqaAppPersistence pepqaAppPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<PepqaAppDTO> dtos=pepqaAppPersistence.getPepqaApps();
		for(PepqaAppDTO dto:dtos){
			pepqaAppPersistence.deletePepqaApp(dto.getId());
		}
	}

	private List<PepqaAppDTO> data=new ArrayList<PepqaAppDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			PepqaAppDTO pdto=new PepqaAppDTO();
			pdto.setName(generateRandom(String.class));
			pdto=pepqaAppPersistence.createPepqaApp(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createPepqaAppTest(){
		PepqaAppDTO ldto=new PepqaAppDTO();
		ldto.setName(generateRandom(String.class));
		
		
		PepqaAppDTO result=pepqaAppLogicService.createPepqaApp(ldto);
		
		Assert.assertNotNull(result);
		
		PepqaAppDTO pdto=pepqaAppPersistence.getPepqaApp(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
	}
	
	@Test
	public void getPepqaAppsTest(){
		List<PepqaAppDTO> list=pepqaAppLogicService.getPepqaApps();
		Assert.assertEquals(list.size(), data.size());
        for(PepqaAppDTO ldto:list){
        	boolean found=false;
            for(PepqaAppDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getPepqaAppTest(){
		PepqaAppDTO pdto=data.get(0);
		PepqaAppDTO ldto=pepqaAppLogicService.getPepqaApp(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
        
	}
	
	@Test
	public void deletePepqaAppTest(){
		PepqaAppDTO pdto=data.get(0);
		pepqaAppLogicService.deletePepqaApp(pdto.getId());
        PepqaAppDTO deleted=pepqaAppPersistence.getPepqaApp(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updatePepqaAppTest(){
		PepqaAppDTO pdto=data.get(0);
		
		PepqaAppDTO ldto=new PepqaAppDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		
		
		pepqaAppLogicService.updatePepqaApp(ldto);
		
		
		PepqaAppDTO resp=pepqaAppPersistence.getPepqaApp(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
	}
	
	@Test
	public void getPepqaAppPaginationTest(){
		
		PepqaAppPageDTO dto1=pepqaAppLogicService.getPepqaApps(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		PepqaAppPageDTO dto2=pepqaAppLogicService.getPepqaApps(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(PepqaAppDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(PepqaAppDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(PepqaAppDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(PepqaAppDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        PepqaAppPageDTO dto3=pepqaAppLogicService.getPepqaApps(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(PepqaAppDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(PepqaAppDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}