/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.usuario.master.persistence.entity;

import co.edu.uniandes.csw.PepqaAppV3.usuario.persistence.entity.UsuarioEntity;
import co.edu.uniandes.csw.PepqaAppV3.usuario.persistence.entity.UsuarioEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(UsuariocontactoUsEntityId.class)
@NamedQueries({
    @NamedQuery(name = "UsuariocontactoUsEntity.getByMasterId", query = "SELECT  u FROM UsuariocontactoUsEntity u WHERE u.usuarioId=:usuarioId"),
    @NamedQuery(name = "UsuariocontactoUsEntity.deleteUsuariocontactoUsEntity", query = "DELETE FROM UsuariocontactoUsEntity u WHERE u.usuarioId=:usuarioId and  u.contactoUsId=:contactoUsId")
})
public class UsuariocontactoUsEntity implements Serializable {

    @Id
    @Column(name = "usuarioId")
    private Long usuarioId;
    @Id
    @Column(name = "contactoUsId")
    private Long contactoUsId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuarioId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity usuarioIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "contactoUsId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity contactoUsIdEntity; 

    public UsuariocontactoUsEntity() {
    }

    public UsuariocontactoUsEntity(Long usuarioId, Long contactoUsId) {
        this.usuarioId =usuarioId;
        this.contactoUsId = contactoUsId;
    }

    public Long getUsuarioId() {
        return usuarioId;
    }

    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }

    public Long getContactoUsId() {
        return contactoUsId;
    }

    public void setContactoUsId(Long contactoUsId) {
        this.contactoUsId = contactoUsId;
    }

    public UsuarioEntity getUsuarioIdEntity() {
        return usuarioIdEntity;
    }

    public void setUsuarioIdEntity(UsuarioEntity usuarioIdEntity) {
        this.usuarioIdEntity = usuarioIdEntity;
    }

    public UsuarioEntity getContactoUsIdEntity() {
        return contactoUsIdEntity;
    }

    public void setContactoUsIdEntity(UsuarioEntity contactoUsIdEntity) {
        this.contactoUsIdEntity = contactoUsIdEntity;
    }

}
