/* ========================================================================
 * Copyright 2014 PepqaAppV3
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 PepqaAppV3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.PepqaAppV3.pepqaapp.master.persistence.entity;

import co.edu.uniandes.csw.PepqaAppV3.usuario.persistence.entity.UsuarioEntity;
import co.edu.uniandes.csw.PepqaAppV3.pepqaapp.persistence.entity.PepqaAppEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(PepqaAppusuariosEntityId.class)
@NamedQueries({
    @NamedQuery(name = "PepqaAppusuariosEntity.getByMasterId", query = "SELECT  u FROM PepqaAppusuariosEntity u WHERE u.pepqaAppId=:pepqaAppId"),
    @NamedQuery(name = "PepqaAppusuariosEntity.deletePepqaAppusuariosEntity", query = "DELETE FROM PepqaAppusuariosEntity u WHERE u.pepqaAppId=:pepqaAppId and  u.usuariosId=:usuariosId")
})
public class PepqaAppusuariosEntity implements Serializable {

    @Id
    @Column(name = "pepqaAppId")
    private Long pepqaAppId;
    @Id
    @Column(name = "usuariosId")
    private Long usuariosId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "pepqaAppId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity pepqaAppIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuariosId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity usuariosIdEntity; 

    public PepqaAppusuariosEntity() {
    }

    public PepqaAppusuariosEntity(Long pepqaAppId, Long usuariosId) {
        this.pepqaAppId =pepqaAppId;
        this.usuariosId = usuariosId;
    }

    public Long getPepqaAppId() {
        return pepqaAppId;
    }

    public void setPepqaAppId(Long pepqaAppId) {
        this.pepqaAppId = pepqaAppId;
    }

    public Long getUsuariosId() {
        return usuariosId;
    }

    public void setUsuariosId(Long usuariosId) {
        this.usuariosId = usuariosId;
    }

    public UsuarioEntity getPepqaAppIdEntity() {
        return pepqaAppIdEntity;
    }

    public void setPepqaAppIdEntity(UsuarioEntity pepqaAppIdEntity) {
        this.pepqaAppIdEntity = pepqaAppIdEntity;
    }

    public UsuarioEntity getUsuariosIdEntity() {
        return usuariosIdEntity;
    }

    public void setUsuariosIdEntity(UsuarioEntity usuariosIdEntity) {
        this.usuariosIdEntity = usuariosIdEntity;
    }

}
